import type { Metadata } from "next";
import { Open_Sans, Montserrat } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const montSerrat = Montserrat({
  variable: "--font-mont-serrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Apex Builders Co.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${montSerrat.variable} antialiased bg-bgcolor text-textcolor`}
      >
        {children}
      </body>
    </html>
  );
}
